# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb6743514942d1ed4575e091d347de05fd820187cbf6c797834d380b4d3e005ac8d4a1ee4c8c74f9263453ef270163a10d84a6057397773e142a3a169b420cfb

test:
  secret_key_base: 80845017125f44771025d2ecd5b014203337f772b6979240536b8fbe898cf915ccc5abb675f111f91be364bd3492db37fc3885a826680a7628f3abe62f8b7a8f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
